# Generated by Django 3.2.23 on 2025-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the studio item or task.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item.', null=True)),
                ('is_checked', models.BooleanField(default=False, help_text='Check if the item is completed or marked.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the item was last updated.')),
            ],
            options={
                'verbose_name': 'Studio Item',
                'verbose_name_plural': 'Studio Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
