# Generated by Django 3.2.23 on 2025-07-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the client.', max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, help_text="Client's email address (optional).", max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Client's phone number (optional).", max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this client currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the client record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the client record was last updated.')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year of the payment.')),
                ('month', models.IntegerField(help_text='The month of the payment (1-12).')),
                ('is_paid', models.BooleanField(default=False, help_text='Check if the payment for this month is made.')),
                ('paid_on', models.DateField(blank=True, help_text='Date the payment was marked as paid (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this payment record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this payment record was last updated.')),
                ('client', models.ForeignKey(help_text='The client associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='studio_content.client')),
            ],
            options={
                'verbose_name': 'Monthly Payment',
                'verbose_name_plural': 'Monthly Payments',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='StudioItem',
        ),
    ]
