# Generated by Django 3.2.23 on 2025-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0002_auto_20250717_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='client',
            name='rd_number',
            field=models.CharField(default=1, help_text='Unique RD number for the client.', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount paid for this month (optional).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Full name of the client.', max_length=200),
        ),
    ]
